       SUBROUTINE OPENF(NAME)
       CHARACTER NAME*40
         NUM=0
         DO I=1,40
          IF(NAME(I:I).NE.' ')NUM=NUM+1
         ENDDO
       OPEN(1,FILE=NAME(1:NUM), STATUS='UNKNOWN')
       OPEN(2,FILE=NAME(1:NUM)//'.RES',STATUS='UNKNOWN')
       OPEN(3,FILE=NAME(1:NUM)//'.ERO',STATUS='UNKNOWN')
       RETURN
       END
