PROGRAM TRUSS
IMPLICIT REAL*8 (A-H,O-Z)
IMPLICIT INTEGER*4 (I-N)
CHARACTER NAME*40
COMMON /AT/A(18000000)
COMMON /IAT/IA(2000000)
A=0;IA=0
WRITE(*,*)'INPUT FILE NAME?';READ(*,*)NAME;CALL OPENF(NAME)
CALL DATAIN(NP,NE,NF,ND,NDF,NPF,NM,NR,NCF,
     &   IME,INAE,IIT,ILMT,IMAXA,           
&   IX,IY,IZ,IRR,IAE,IPF,ICKK,IDIST,IFTOOL,IFF,IPP,ISG,ISM)
       CALL FLMT(NP,NE,NN,NN1,NR,RR,ND,NF,NDF,
&   IA(IME+1),IA(IIT+1),IA(ILMT+1))
CALL FMAXA(NN1,NE,IA(ILMT+1),IA(IMAXA+1),NWK,NPF,NDF)
       CALL CONKB(NP,NE,NM,NWK,IA(IME+1),A(IX+1),
&   A(IY+),A(IZ+1),A(IAE+),IA(INAE+1),
     &   IA(ILMT+1),IA(IMAXA+1),A(ICKK+1),NN1)
CALL MKFORCE(NP,NF,NPF,NCF,NN,
&   IA(IIT+1),A(IPF+1),A(IPP+1),A(IFTOOL+1))
       CALL LDLT(A(ICKK+1),IA(IMAXA+1),NN,0,3,NWK,NN1)
       CALL RESOLVE(A(ICKK+1),A(IFTOOL+1),IA(IMAXA+1),NN,NWK,NN1)
CALL DISPLS(NP,NE,NF,NPF,NM,NN,IA(IIT+1),A(IFTOOL+1),
&  A(IDIST+1),A(IAE+1),IA(INAE+1),A(IX+1),A(IY+1),A(IZ+1),
&  A(IPP+1),A(IFF+1),A(ISG+1),A(ISM+1))
CALL DATAOUT(NP,NE,NF,NPF,NM,NN,IA(IIT+1),A(IFTOOL+1),
&  A(IDIST+1),A(IAE+1),IA(INAE+1),A(IX+1),A(IY+1),A(IZ+1),
&  A(IPP+1),A(IFF+1),A(ISG+1),A(ISM+1))
CALL CLOSF
END
