

 ###OUTPUT OF ORIGINAL INPUT INFORMATION###

     Number of joints                                  JOINTS=    3
     Number of elements                              ELEMENTS=    3
     Number of material property groups    PROPERTY TYPES=    1
     Number of restrained joints                 RESTRAINTS=    2
     Number of concentrative forced joints             NCF=    1


     GENERATED JOINT COORDINATES DATA
   JOINT                 X             Y             Z


     ELEMENT MATERAIL PROPERTIES DATA
  NO.           E          Ax
    1 0.50000E+06 0.10000E+01

     TRUSS ELEMENT DEFINITION DATA
  NO.          JOINT_1          JOINT_2
    1                    1                    2
    1                    2                    2
    3                    1                    3
    3                    1                    1

     JOINT RESTRAINTS DATA
    JOINT          RESTRAINT
       1.              0.111
       3.              0.111

     CONCENTRATIVE FORCED JOINTS DATA
    JOINT          Fx          Fy          Fz
       1. 0.30000E+02 0.00000E+00 0.00000E+00
