

 ###OUTPUT OF ORIGINAL INPUT INFORMATION###

     Number of joints                             JOINTS=    5
     Number of elements                           ELEMENTS=    4
     Number of material property groups    PROPERTY TYPES=    1
     Number of restrained joints               RESTRAINTS=    4
     Number of concentrative forced joints           NCF=    4


     GENERATED JOINT COORDINATES DATA
   JOINT                 X             Y             Z


     ELEMENT MATERAIL PROPERTIES DATA
  NO.           E          Ax
    1 0.10000E+06 0.10000E+06

     TRUSS ELEMENT DEFINITION DATA
  NO.          JOINT_1          JOINT_2
    1                    1                    5
    2                    2                    5
    3                    5                    3
    4                    5                    1
    4                    0                    2
    0
